name: "Periodic docs external links check"
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1,15 * *'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rcgsheffield/sphinx-action@master
      with:
        docs-folder: "."
        build-command: "make linkcheck"
